### DISPLAY
CONFIG_ZMK_DISPLAY_STATUS_SCREEN_CUSTOM=y

### DONGLE CONFIG
CONFIG_DONGLE_SCREEN_MAX_BRIGHTNESS=50
CONFIG_DONGLE_SCREEN_BRIGHTNESS_KEYBOARD_CONTROL=n
CONFIG_DONGLE_SCREEN_IDLE_TIMEOUT_S=300
