manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # prospetor dongle display
    - name: carrefinho                        
      url-base: https://github.com/carrefinho
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    # prospector dongle display
    - name: prospector-zmk-module                 
      remote: carrefinho                      
      revision: main              
  self:
    path: config
