manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    # dongle screen
    - name: SonDinh5310                       
      url-base: https://github.com/SonDinh5310
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: main
      import: app/west.yml
    - name: zmk-dongle-screen
      remote: SonDinh5310
      revision: main         
  self:
    path: config
